### NumPy Exercises: Student Performance Dataset

#### 📋 Dataset Information

**Dataset**: Students Performance in Exams  
**Source**: https://www.kaggle.com/datasets/spscientist/students-performance-in-exams  
**Size**: 1,000 students  

**Columns**:
- `gender`: Student's gender (male/female)
- `race/ethnicity`: Student's ethnic group (group A, B, C, D, E)
- `parental level of education`: Parent's education level
- `lunch`: Type of lunch (standard/free or reduced)
- `test preparation course`: Completed test prep course (completed/none)
- `math score`: Score in math (0-100)
- `reading score`: Score in reading (0-100)
- `writing score`: Score in writing (0-100)

In [1]:
## NO NEED CODE HERE
import numpy as np

# Load the dataset
data = np.genfromtxt('Data/StudentsPerformance.csv', delimiter=',', 
                     dtype=None, encoding='utf-8', names=True)

def clean_and_convert(arr):
    return np.array([int(str(x).strip('"').strip("'")) for x in arr])

# For easier manipulation, separate numeric scores into a 2D array
# math_scores = data['math_score']
# reading_scores = data['reading_score']
# writing_scores = data['writing_score']

math_scores = clean_and_convert(data['math_score'])
reading_scores = clean_and_convert(data['reading_score'])
writing_scores = clean_and_convert(data['writing_score'])

# Create a 2D array with all scores
scores = np.column_stack([math_scores, reading_scores, writing_scores])

print("Dataset loaded successfully!")
print(f"Number of students: {len(data)}")
print(f"Scores array shape: {scores.shape}")

Dataset loaded successfully!
Number of students: 1000
Scores array shape: (1000, 3)


### Task 1: Explore the Dataset Structure
**Instructions**:
1. Print the shape of the `scores` array
2. Print the data type of the `scores` array
3. Calculate the total number of elements in the `scores` array
4. Print the first 5 students' scores
5. Print the last 3 students' scores

In [2]:
# TODO: Your code here
# 1. Shape
print("Shape:", scores.shape)

# 2. Data type
print("Data type:", scores.dtype)

# 3. Total elements
print("Total elements:", scores.size)

# 4. First 5 students
print("First 5 students:\n", scores[:5])

# 5. Last 3 students
print("Last 3 students:\n", scores[-3:])

Shape: (1000, 3)
Data type: int64
Total elements: 3000
First 5 students:
 [[72 72 74]
 [69 90 88]
 [90 95 93]
 [47 57 44]
 [76 78 75]]
Last 3 students:
 [[59 71 65]
 [68 78 77]
 [77 86 86]]


### Task 2: Access Specific Student Data
**Instructions**:
1. Get the scores of the 10th student (remember: Python uses 0-indexing)
2. Get the math score of the 50th student
3. Get the writing score of the 100th student
4. Get all three scores for student at index 25
5. Create a new array containing scores of students at indices 0, 5, and 10

In [3]:
# TODO: Your code here
# 1. 10th student (all scores)
student_10 = scores[9]
print("Student 10 scores:", student_10)

# 2. Math score of 50th student
math_50 = scores[49, 0]
print("Math score of student 50:", math_50)

# 3. Writing score of 100th student
writing_100 = scores[99, 2]
print("Writing score of student 100:", writing_100)

# 4. All scores for student 25
student_25 = scores[24]
print("Student 25 scores:", student_25)

# 5. Scores for students 0, 5, and 10
selected_students = scores[[0, 5, 10]]
print("Selected students:\n", selected_students)


Student 10 scores: [38 60 50]
Math score of student 50: 82
Writing score of student 100: 62
Student 25 scores: [74 71 80]
Selected students:
 [[72 72 74]
 [71 83 78]
 [58 54 52]]


### Task 3: Filter Students by Performance
**Instructions**:
1. Find all students who scored above 80 in math
2. Find all students who scored below 50 in reading
3. Find all students who scored exactly 75 in writing
4. Count how many students scored above 90 in math
5. Find students who scored between 60 and 70 (inclusive) in reading

In [4]:
# TODO: Your code here
# 1. Students with math > 80
math_above_80 = scores[scores[:, 0] > 80]
print(f"Students with math > 80: {len(math_above_80)} students")
print(math_above_80)

# 2. Students with reading < 50
reading_below_50 = scores[scores[:, 1] < 50]
print(f"\nStudents with reading < 50: {len(reading_below_50)} students")

# 3. Students with writing exactly 75
writing_75 = scores[scores[:, 2] == 75]
print(f"\nStudents with writing exactly 75: {len(writing_75)} students")

# 4. Count students with math > 90
math_above_90_count = np.sum(scores[:, 0] > 90)
print(f"\nCount of students with math > 90: {math_above_90_count}")

# 5. Students with reading between 60-70
reading_60_70 = scores[(scores[:, 1] >= 60) & (scores[:, 1] <= 70)]
print(f"\nStudents with reading between 60-70: {len(reading_60_70)} students")


Students with math > 80: 176 students
[[ 90  95  93]
 [ 88  95  92]
 [ 88  89  86]
 [ 97  87  82]
 [ 81  81  79]
 [ 82  84  82]
 [ 88  78  75]
 [ 82  85  86]
 [ 85  91  89]
 [ 98  86  90]
 [ 87 100 100]
 [ 99 100 100]
 [ 84  77  74]
 [ 91  89  92]
 [ 88  93  93]
 [ 83  80  73]
 [ 87  95  86]
 [ 82  82  74]
 [ 89  84  82]
 [ 87  74  70]
 [ 88  73  78]
 [ 88  84  75]
 [100 100  93]
 [ 82  78  74]
 [ 81  92  91]
 [ 96 100 100]
 [ 94  88  78]
 [ 81  91  87]
 [ 97 100 100]
 [ 82  62  62]
 [ 81  80  76]
 [ 87  91  81]
 [ 84  83  75]
 [ 83  86  88]
 [ 87  85  73]
 [ 86  80  75]
 [ 88  95  94]
 [ 92  87  78]
 [ 83  82  84]
 [ 84  80  80]
 [ 85  76  71]
 [ 89  76  74]
 [ 99  93  90]
 [ 88  92  95]
 [ 88  85  76]
 [ 83  78  73]
 [ 85  92  93]
 [ 81  82  82]
 [ 97  82  88]
 [ 88  75  76]
 [ 86  73  70]
 [ 90  87  75]
 [ 81  78  81]
 [ 99  87  81]
 [ 83  72  78]
 [ 82  90  94]
 [ 82  75  77]
 [ 90  78  81]
 [ 83  93  95]
 [ 87  74  76]
 [ 85  84  78]
 [ 84  77  71]
 [ 82  97  96]
 [ 85  95 100]
 [

### Task 4: Compare Two Subjects
**Instructions**:
1. Find students who scored higher in math than in reading
2. Find students who scored the same in reading and writing
3. Count how many students scored higher in writing than in math
4. Find the student(s) with the largest difference between math and writing scores
5. Calculate the average difference between reading and writing scores

In [5]:
# TODO: Your code here
# 1. Students with math > reading
math_better_than_reading = scores[scores[:, 0] > scores[:, 1]]
print(f"Students with math > reading: {len(math_better_than_reading)}")

# 2. Students with reading == writing
same_reading_writing = scores[scores[:, 1] == scores[:, 2]]
print(f"Students with reading = writing: {len(same_reading_writing)}")

# 3. Count students with writing > math
count_writing_better_math = np.sum(scores[:, 2] > scores[:, 0])
print(f"Students with writing > math: {count_writing_better_math}")

# 4. Largest difference between math and writing
diff_math_writing = np.abs(scores[:, 0] - scores[:, 2])
max_diff = np.max(diff_math_writing)
max_diff_indices = np.where(diff_math_writing == max_diff)[0]
print(f"\nLargest difference between math and writing: {max_diff}")
print("Student(s) with largest difference:")

for idx in max_diff_indices:
    print(f"    Student index {idx}:")
    print(f"    Scores: Math = {scores[idx, 0]}, Reading = {scores[idx, 1]}, Writing = {scores[idx, 2]}")
    
# 5. Average difference between reading and writing
avg_diff = np.mean(np.abs(scores[:, 1] - scores[:, 2]))
print(f"\nAverage difference between reading and writing: {avg_diff:.2f}")


Students with math > reading: 349
Students with reading = writing: 85
Students with writing > math: 560

Largest difference between math and writing: 28
Student(s) with largest difference:
    Student index 414:
    Scores: Math = 51, Reading = 72, Writing = 79

Average difference between reading and writing: 3.74


### Task 5: Score Distribution Analysis 
Analyze how scores are distributed across different ranges without using histograms or binning functions

**Instructions**:

1. **Create score bins**: Define 10 ranges for scores:
   - Bin 0: 0-9 points
   - Bin 1: 10-19 points
   - Bin 2: 20-29 points
   - ... and so on ...
   - Bin 9: 90-100 points

2. **Count students in each bin for math scores**: Use a loop to go through all math scores and count how many fall into each bin.

3. **Display the distribution**: Print the count for each bin in a readable format.

4. **Find the most common range**: Determine which bin has the most students (the mode range).

5. **Calculate cumulative distribution**: For each bin, calculate how many students scored at or below that range.

6. **Repeat for reading and writing**: Apply the same analysis to the other two subjects.

7. **Compare distributions**: Identify which subject has the most students in the highest bin (90-100).

In [6]:
#TODO: your code here

def analyze_distribution(subject_scores, subject_name):
# 1. Create an array to store counts for 10 bins
    bins = np.zeros(10, dtype=int)

    # 2. Count students in each bin
    for score in subject_scores:
        bin_idx = min(score // 10, 9)  # 0-9 => bin 0
        bins[bin_idx] += 1
        
    # 3. Display the distribution
    print(f"\n{subject_name} Score Distribution:")
    for i in range(10):
        if i < 9:
            range_str = f"[{i*10}, {i*10+10})"
        else:
            range_str = "[90, 100]"
        print(f"    Bin {i} {range_str}: {bins[i]} students")

    # 4. Find the most common range
    most_common_bin = np.argmax(bins)
    print(f"\nMost common range: Bin {most_common_bin} ({most_common_bin*10}-{most_common_bin*10+9 if most_common_bin < 9 else 100}) with {bins[most_common_bin]} students")

    # 5. Calculate cumulative distribution
    cumulative = np.cumsum(bins)
    print(f"\nCumulative Distribution ({subject_name}):")
    for i in range(10):
        range_str = f"≤{i*10+9}" if i < 9 else "≤100"
        print(f"    {range_str}: {cumulative[i]} students ({cumulative[i]/len(subject_scores)*100:.1f}%)")
        
    return bins

math_bins = analyze_distribution(math_scores, "Math")

# 6. Repeat for reading and writing
reading_bins = analyze_distribution(reading_scores, "Reading")
writing_bins = analyze_distribution(writing_scores, "Writing")

# 7. Compare distributions 
print(f"\nHighest Bin (90-100) Comparison:")
print(f"    Math: {math_bins[9]} students")
print(f"    Reading: {reading_bins[9]} students")
print(f"    Writing: {writing_bins[9]} students")
highest_subject = ["Math", "Reading", "Writing"][np.argmax([math_bins[9], reading_bins[9], writing_bins[9]])]
print(f"    Subject with most students in 90-100 range: {highest_subject}")



Math Score Distribution:
    Bin 0 [0, 10): 2 students
    Bin 1 [10, 20): 2 students
    Bin 2 [20, 30): 10 students
    Bin 3 [30, 40): 26 students
    Bin 4 [40, 50): 95 students
    Bin 5 [50, 60): 188 students
    Bin 6 [60, 70): 268 students
    Bin 7 [70, 80): 216 students
    Bin 8 [80, 90): 135 students
    Bin 9 [90, 100]: 58 students

Most common range: Bin 6 (60-69) with 268 students

Cumulative Distribution (Math):
    ≤9: 2 students (0.2%)
    ≤19: 4 students (0.4%)
    ≤29: 14 students (1.4%)
    ≤39: 40 students (4.0%)
    ≤49: 135 students (13.5%)
    ≤59: 323 students (32.3%)
    ≤69: 591 students (59.1%)
    ≤79: 807 students (80.7%)
    ≤89: 942 students (94.2%)
    ≤100: 1000 students (100.0%)

Reading Score Distribution:
    Bin 0 [0, 10): 0 students
    Bin 1 [10, 20): 1 students
    Bin 2 [20, 30): 7 students
    Bin 3 [30, 40): 18 students
    Bin 4 [40, 50): 64 students
    Bin 5 [50, 60): 164 students
    Bin 6 [60, 70): 233 students
    Bin 7 [70, 80): 264 

### Task 6: Student Consistency Analysis
Identify students who have very consistent scores across all three subjects without using variance or standard deviation functions.

**Instructions**:

1. **Calculate score range for each student**: For each student, find the difference between their highest and lowest score among the three subjects.

2. **Define consistency threshold**: Students are "consistent" if their range is 10 points or less (all three scores within 10 points of each other).

3. **Count consistent students**: Count how many students meet the consistency criteria.

4. **Find the most consistent student**: Identify the student with the smallest range (most consistent).

5. **Find the least consistent student**: Identify the student with the largest range (most variable).

6. **Create consistency categories**:
   - Very Consistent: range ≤ 5
   - Consistent: range 6-10
   - Moderate: range 11-20
   - Variable: range 21-30
   - Highly Variable: range > 30

7. **Count students in each category**: Display the distribution.

8. **Analyze patterns**: Among consistent students, which subject combinations tend to be similar?

In [7]:
# TODO: Your code here

# 1. Calculate score range for each student
score_ranges = np.max(scores, axis=1) - np.min(scores, axis=1)

# 2 & 3. Count consistent students 
consistent_mask = score_ranges <= 10
consistent_students = np.sum(consistent_mask)
print(f"Number of consistent students (range ≤ 10): {consistent_students}")

# 4. Find most consistent student
min_range = np.min(score_ranges)
most_consistent_idx = np.argmin(score_ranges)
print(f"\nMost consistent student (index {most_consistent_idx}):")
print(f"    Scores: {scores[most_consistent_idx]}, Range: {min_range}")

# 5. Find least consistent student
max_range = np.max(score_ranges)
least_consistent_idx = np.argmax(score_ranges)
print(f"\nLeast consistent student (index {least_consistent_idx}):")
print(f"    Scores: {scores[least_consistent_idx]}, Range: {max_range}")

# 6. Create consistency categories
categories = {
    "Very Consistent (≤5)": np.sum(score_ranges <= 5),
    "Consistent (6–10)": np.sum((score_ranges >= 6) & (score_ranges <= 10)),
    "Moderate (11–20)": np.sum((score_ranges >= 11) & (score_ranges <= 20)),
    "Variable (21–30)": np.sum((score_ranges >= 21) & (score_ranges <= 30)),
    "Highly Variable (>30)": np.sum(score_ranges > 30)
}

# 7. Count students in each category
print("\nConsistency Distribution:")
for cat, count in categories.items():
    print(f"    {cat}: {count} students")

# 8. Analyze patterns among consistent students
consistent_students = scores[consistent_mask]
print(f"\nAnalyzing {len(consistent_students)} consistent students")

# Check which subject pairs are most similar
math_reading_diff = np.abs(consistent_students[:, 0] - consistent_students[:, 1])
math_writing_diff = np.abs(consistent_students[:, 0] - consistent_students[:, 2])
reading_writing_diff = np.abs(consistent_students[:, 1] - consistent_students[:, 2])

pair_names = ["Math-Reading", "Math-Writing", "Reading-Writing"]
pair_diffs = [math_reading_diff, math_writing_diff, reading_writing_diff]
avg_diffs = [np.mean(d) for d in pair_diffs]

print("Average absolute difference between subjects (consistent students):")
for name, avg in zip(pair_names, avg_diffs):
    print(f"    {name}: {avg:.2f}")

# Find most common similar pair
most_similar_idx = np.argmin(avg_diffs)
print(f"Most similar subject pair: {pair_names[most_similar_idx]} (avg diff: {avg_diffs[most_similar_idx]:.2f})")


Number of consistent students (range ≤ 10): 596

Most consistent student (index 157):
    Scores: [60 60 60], Range: 0

Least consistent student (index 371):
    Scores: [45 73 70], Range: 28

Consistency Distribution:
    Very Consistent (≤5): 231 students
    Consistent (6–10): 365 students
    Moderate (11–20): 372 students
    Variable (21–30): 32 students
    Highly Variable (>30): 0 students

Analyzing 596 consistent students
Average absolute difference between subjects (consistent students):
    Math-Reading: 4.41
    Math-Writing: 4.73
    Reading-Writing: 3.25
Most similar subject pair: Reading-Writing (avg diff: 3.25)
